### ISSUE TITLE
InExUtils Interface

### ISSUE THREAD

**Issue by masood-ahmad** [Manan-Joshi/inexutils#1]
Hi Manan,
I tested this utility and found it very helpful. I also wrote an article on InDesignsSecrets.com:
https://indesignsecrets.com/solution-for-packaging-files-with-missing-plug-ins.php

Two things to add on to the Utility, if possible.
1. The Utility should pop-up a message after the process is done.
2. The pop-up should also ask whether the user wants to save the file or not.
OR
The utility should auto save the file once the process is done.

In addition, people are also looking for other versions of the tool. Please share if possible.

**Comment by Manan-Joshi** [comment]
Hi Masood, Thanks for writing that article I did read that and apologies for being so late in reverting. I am not sure how I missed these open issues. Well, I will look into your suggestions and implement them soon. The decision to not save the files was deliberate, as I wanted the user to save the file after verifying that the document conversion did not break anything. Adding the completed message is a good idea and can be done easily. Thank you for your valuable suggestions. I will post an update soon.
