### ISSUE TITLE
inexutils for INDD CC 2015?

### ISSUE THREAD

**Issue by marco-bien** [Manan-Joshi/inexutils#2]
We appreciate very much what inexutils does. Because of a special customer plugin we're currently working with the InDesign CC 2015 Version. So how about a release of an inexutils version for this? We would contribute our testing experiences.

**Comment by Manan-Joshi** [comment]
Hi Marco, first up, apologies for replying so late, I totally missed these notifications. I am not sure if you still are looking for such an old version of the plugin, let me know if I can be of any assistance on the matter now.

**Comment by marco-bien** [comment]
Hi  Manan-Joshi, thanky for your reply. No, I don't need it anymore, so I close this one.
