### ISSUE TITLE
Trial expired

### ISSUE THREAD

**Issue by hooperjch** [Manan-Joshi/inexutils#3]
My trial expired. I need to know how to get a permanent license. I still have thousands of file that  need processing

**Comment by spopule** [comment]
I also get the same error running InDesign 2020. Is there a paid version?

**Comment by Manan-Joshi** [comment]
First up, sorry for being late to respond, I don't know how I missed looking at the filed issues. Anyways, yes there is a paid version, the trial version runs for seven days only. You can send out your requirements to me on the email id mentioned on the popup that declares the expiry of the demo version, i.e. mananjoshi227[at]gmail.com
