### ISSUE TITLE
No information about the Plugin being a Trial prior to downloading/using it

### ISSUE THREAD

**Issue by HigH-HawK** [Manan-Joshi/inexutils#4]
Hi,

It's great that someone actually sat down and created a plugin to get rid of the pesky missing plugins in an InDesign document. And I do agree, that the person should be able to get some coins for his work and time.

However, it's kind of annoying that there is no information about it being a Trial prior to download and/or using it. I have suggested this piece of software to one of my customers and they started complaining that I suggested TRIAL software. This scratches on the credibility vest.

Please add the TRIAL information in your Readme so people have a bit more choice to think before they actually download it

**Comment by Manan-Joshi** [comment]
Hi Chris,
I acknowledge that the Readme isn't updated with information about the trial/liecense information. However, I would like to make the following points in response to the experience shared by your client.

- After installation when you launch Indesign, after the first launch you get a prompt at startup everytime that clearly mentiones that this is a trial version and for a licensed version the user can contact me on my email id mentioened. I quote the exact message displayed
"Enjoy your INEXUtils trial.\nFor licensed version/reporting bugs contact at mananjoshi227@gmail.com"

- Secondly I don't understand the reason for the client's annoyance as the plugin works without restriction during the trial period with displaying the message described above. If they are annoyed by the message about trial/expired trial, thay can always remove the plugin manually that you could say is the only extra work they would have to do. Infact I have many users who use the plugin during the trial period, clean up their documents and never buy the full version which is fine by me.

I hope you understand that although I do expect to sell the plugin but I channelize my limited time to make it work on successive InDesign versions and don't even market it as such, let alone mislead with confusing information. I would anyhow update the README file as well.

Thanks for sharing the feedback I appreciate it.

**Comment by Manan-Joshi** [comment]
I have update the README with information about the trial version.
